# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opodapp', '0002_auto_20171211_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='merusak',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
