# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opodapp', '0003_order_merusak'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='merusak',
        ),
    ]
