# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opodapp', '0004_remove_order_merusak'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CmpltOrder',
        ),
    ]
