# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opodapp', '0006_cmpltorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmpltorder',
            name='Nama_Order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Nama_Order',
        ),
    ]
