# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 16:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opodapp', '0007_auto_20171213_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomor_PO', models.CharField(max_length=100)),
                ('Item_Desc', models.CharField(max_length=100)),
                ('U_of_m', models.CharField(max_length=10)),
                ('Qty', models.CharField(max_length=100)),
                ('Tggl_Pengiriman', models.DateField()),
                ('Mesin', models.CharField(max_length=10)),
                ('Tggl_Mulai_Produksi', models.DateTimeField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cmpltorder',
            name='Tggl_Mulai_Produksi',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 17, 16, 22, 6, 518322), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cmpltorder',
            name='Tggl_Selesai_Produksi',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 17, 16, 22, 17, 974743), max_length=100),
            preserve_default=False,
        ),
    ]
