# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opodapp', '0008_auto_20171217_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='Keterangan',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cmpltorder',
            name='Tggl_Mulai_Produksi',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cmpltorder',
            name='Tggl_Selesai_Produksi',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='production',
            name='Tggl_Mulai_Produksi',
            field=models.DateTimeField(),
        ),
    ]
