# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opodapp', '0010_auto_20171217_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='Tggl_Mulai_Produksi',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
