# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opodapp', '0011_auto_20171217_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmpltorder',
            name='Tggl_Mulai_Produksi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cmpltorder',
            name='Tggl_Pengiriman',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cmpltorder',
            name='Tggl_Selesai_Produksi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Tggl_Pengiriman',
            field=models.DateField(blank=True, null=True),
        ),
    ]
