# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opodapp', '0012_auto_20171217_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Tggl_Pengiriman',
            field=models.CharField(default='24-12-2017', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='production',
            name='Tggl_Mulai_Produksi',
            field=models.CharField(default='24-12-2017', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='production',
            name='Tggl_Pengiriman',
            field=models.CharField(default='24-12-2017', max_length=50),
            preserve_default=False,
        ),
    ]
