# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opodapp', '0013_auto_20171217_1743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CmpltOrder',
        ),
    ]
