# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opodapp', '0015_auto_20171217_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmpltOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomor_PO', models.CharField(max_length=100)),
                ('Item_desc', models.CharField(max_length=100)),
                ('U_of_m', models.CharField(max_length=10)),
                ('Qty', models.CharField(max_length=100)),
                ('Keterangan', models.CharField(max_length=100)),
                ('Tggl_Pengiriman', models.CharField(max_length=100)),
                ('Mesin', models.CharField(max_length=10)),
                ('Tggl_Mulai_Produksi', models.CharField(max_length=100)),
                ('Tggl_Selesai_Produksi', models.CharField(max_length=100)),
            ],
        ),
    ]
