# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opodapp', '0017_cmpltorder_output'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmpltorder',
            old_name='Output',
            new_name='Batch_Output_Berat',
        ),
        migrations.AddField(
            model_name='cmpltorder',
            name='Batch_Output_Panjang',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cmpltorder',
            name='Batch_Output_Roll',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
