# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opodapp', '0020_auto_20180108_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmpltorder',
            name='Product',
            field=models.CharField(default='QuaSAREX', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='Product',
            field=models.CharField(default='QuaSAREX', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='production',
            name='Product',
            field=models.CharField(default='QuaSAREX', max_length=10),
            preserve_default=False,
        ),
    ]
