# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-01 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opodapp', '0027_auto_20180131_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmpltorder',
            name='Remarks',
            field=models.CharField(default='all good', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='Tggl_Pengiriman',
            field=models.CharField(max_length=100),
        ),
    ]
