# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-17 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opodapp', '0028_auto_20180201_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoEx2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=30)),
                ('Timestamp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CoEx3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=30)),
                ('Timestamp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CoEx4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=30)),
                ('Timestamp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CoEx5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=30)),
                ('Timestamp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CoEx6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=30)),
                ('Timestamp', models.CharField(max_length=100)),
            ],
        ),
    ]
