# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-22 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opodapp', '0029_coex2_coex3_coex4_coex5_coex6'),
    ]

    operations = [
        migrations.AddField(
            model_name='coex2',
            name='Remarks',
            field=models.CharField(default='Test', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coex3',
            name='Remarks',
            field=models.CharField(default='Test', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coex4',
            name='Remarks',
            field=models.CharField(default='Test', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coex5',
            name='Remarks',
            field=models.CharField(default='Test', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coex6',
            name='Remarks',
            field=models.CharField(default='Test', max_length=300),
            preserve_default=False,
        ),
    ]
